### ISSUE TITLE
Performance gains

### ISSUE THREAD

**Issue by neobits** [fluviofx/fluviofx#32]
Hello Lily.
First of all, thanks for this outstanding fluid sim-engine built in Fluvio, it's very impressive from a technical view point. Right now I'm wondering how to have performance gains with the Fluid System.

Initialize Solver > Space Partitioning > Neighbour Search are a must?
So to get higher framerate: Calc Density and Pressure + Calc Surface Normal + Calc Force blocks can be switched off?

I'm using also a 100k particles, a box Fluid Collider (inverted)  and on output Lit Cubes:

![Editor Stats, nearly 76 fps](https://user-images.githubusercontent.com/33874219/69421748-1b856e80-0d22-11ea-8035-08ed40c039d5.png)
Using nvidia 1660 + 16DDR4 + i7 8300

Unity Visual Effect Asset: [BrickFluidVfx.vfx.txt](https://github.com/fluviofx/fluviofx/files/3879290/BrickFluidVfx.vfx.txt) (please rename by removing the txt extension)

Also, why there's an increase in performance when the mass and size are set both in automatic?

![image](https://user-images.githubusercontent.com/33874219/69422698-9fd8f100-0d24-11ea-9e2c-e9524c7c0eed.png)

Nearly +20fps!

Also, from the technical view, how can we gain performance with the compute scripts builtin fluviofx?
I'm very new to compute shaders and deep graphics programming but I would like to know how to improve (if any) the scripts.

Thanks in advance!

**Comment by lmontoute** [comment]
Hi @neobits,

There are a few things that can help with performance issues. I'll tackle this in order:

> Initialize Solver > Space Partitioning > Neighbour Search are a must?

Yes, these must be enabled in order for the system to work correctly.

> Calc Density and Pressure + Calc Surface Normal + Calc Force blocks can be switched off?

These are also required, as they are the steps that actually calculate the values for the simulation.

> Also, why there's an increase in performance when the mass and size are set both in automatic?

Size should only affect the visual size of particles (though this may affect rendering, and therefore overall performance). Mass however can affect performance based on the other properties of a fluid. I recommend keeping automatic mass checked to retain more accurate physical behavior.

There are a few best practices for keeping good performance:

1. **Check your timestep** - try to make your timestep as large as possible while maintaining stability of your fluid. How large you can go depends entirely on what happens with the fluid. For pooling of liquids or dense areas, a lower timestep isneeded for simulation, which has a higher performance cost.
2. **Check high pressure areas** - the higher the pressure and density of an area of fluid, the higher the performance cost. Check for any excessively high pressure areas of the simulation.
3. **Lower particle counts** - there are many occasions where you can get away with lower particle counts without sacrificing too much visual quality. Try to keep as few particles as possible to achieve the quality you're looking for.
4. **Disable optional features on colliders/remove excess colliders** - Colliders have a large performance impact. Removing these and disabling optional features can help improve performance significantly.

That said, it's important to remember that fluid simulation is expensive _in general_, and 100k fluid particles even on modern hardware can be difficult. It may be possible to augment a smaller simulation with some additional, non-simulated particles in order to improve performance.
